version: "3.7"

services:
  whattoread-nginx:
    container_name: whattoread-nginx-dev
    ports:
        - "8301:80"
    volumes:
      - ./deploy/nginx/dev.conf:/etc/nginx/conf.d/default.conf

  whattoread-php-fpm:
    container_name: whattoread-php-fpm-dev

  whattoread-percona:
    container_name: whattoread-percona-dev
    ports:
      - "3316:3306"
    volumes:
      - whattoread-dev-database-data:/var/lib/mysql

  whattoread-elasticsearch:
    container_name: whattoread-elasticsearch-dev
    environment:
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m -XX:UseAVX=1" #Xms обязательно должно быть равно по размеру Xmx. Размер памяти на ноду
    volumes:
      - whattoread-dev-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"

  whattoread-redis:
    container_name: whattoread-redis-dev
    ports:
      - "6381:6379"
    volumes:
      - ./storage/logs/elasticsearch:/var/log/elasticsearch
      - whattoread-dev-redis-data:/data

volumes:
  whattoread-dev-database-data: # данные БД
  whattoread-dev-elasticsearch-data: # данные Elasticsearch
  whattoread-dev-redis-data: # данные Redis
