version: "3.7"

services:
    whattoread-nginx:
        ports:
            - "8301:80"
        volumes:
          - ./deploy/nginx/dev.conf:/etc/nginx/conf.d/default.conf
        container_name: whattoread-dev-nginx

    whattoread-php-fpm:
        container_name: whattoread-dev-php-fpm

    whattoread-percona:
      container_name: whattoread-dev-percona
      ports:
        - "3316:3306"

volumes:
    whattoread-database-data: # данные БД
