version: "3.7"

services:
    whattoread-nginx:
        image: nginx:1.17
        environment:
            TZ: "Europe/Moscow"
        volumes:
            - ./:/opt/www
        depends_on:
            - whattoread-php-fpm

    whattoread-php-fpm:
        build:
            context: .
            dockerfile: ./deploy/php-fpm/Dockerfile
        volumes:
            - ./deploy/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./app:/opt/www/app
            - ./bootstrap:/opt/www/bootstrap
            - ./config:/opt/www/config
            - ./database:/opt/www/database
            - ./public:/opt/www/public
            - ./resources:/opt/www/resources
            - ./routes:/opt/www/routes
            - ./storage:/opt/www/storage
            - ./tests:/opt/www/tests
            - ./.env:/opt/www/.env
            - ./artisan:/opt/www/artisan
            - ./composer.json:/opt/www/composer.json
            - ./composer.lock:/opt/www/composer.lock
            - ./phpunit.xml:/opt/www/phpunit.xml
        depends_on:
            - whattoread-redis
        environment:
            TZ: "Europe/Moscow"

    whattoread-redis:
        image: redis:6
        environment:
            TZ: "Europe/Moscow"
