version: "3.7"

services:
  whattoread-nginx:
    container_name: whattoread-nginx
    ports:
        - "8300:80"
    volumes:
      - ./deploy/nginx/prod.conf:/etc/nginx/conf.d/default.conf

  whattoread-php-fpm:
    container_name: whattoread-php-fpm

  whattoread-percona:
    container_name: whattoread-percona
    ports:
      - "3306:3306"
    volumes:
      - whattoread-database-data:/var/lib/mysql

  whattoread-redis:
    container_name: whattoread-redis
    ports:
      - "6380:6379"
    volumes:
      - whattoread-redis-data:/data

volumes:
  whattoread-database-data: # данные БД
  whattoread-redis-data: # данные Redis
