version: "3.7"

services:
    whattoread-nginx:
        image: nginx:1.17
        environment:
            TZ: "Europe/Moscow"
        volumes:
            - ./storage/logs/nginx:/var/log/nginx
            - ./:/opt/www
        depends_on:
            - whattoread-php-fpm

    whattoread-php-fpm:
        build:
            context: .
            dockerfile: ./deploy/php-fpm/Dockerfile
        volumes:
            - ./deploy/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./app:/opt/www/app
            - ./bootstrap:/opt/www/bootstrap
            - ./config:/opt/www/config
            - ./database:/opt/www/database
            - ./public:/opt/www/public
            - ./resources:/opt/www/resources
            - ./routes:/opt/www/routes
            - ./storage:/opt/www/storage
            - ./tests:/opt/www/tests
            - ./.env:/opt/www/.env
            - ./artisan:/opt/www/artisan
            - ./composer.json:/opt/www/composer.json
            - ./composer.lock:/opt/www/composer.lock
            - ./phpunit.xml:/opt/www/phpunit.xml
        depends_on:
            - whattoread-percona
            - whattoread-elasticsearch
            - whattoread-redis
        environment:
            TZ: "Europe/Moscow"

    whattoread-percona:
        image: percona:8.0
        restart: always
        environment:
            TZ: "Europe/Moscow"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./deploy/percona/init-testing-db.sql:/docker-entrypoint-initdb.d/init-testing-db.sql
            - ./deploy/percona/dump.sh:/dump.sh
            - ./deploy/percona/restore.sh:/restore.sh
            - ./backups:/home

    whattoread-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
        restart: unless-stopped
        environment:
            - "discovery.type=single-node"
            - "bootstrap.memory_lock=true" #в этой ситуации узел выберет себя ведущим и не присоединится к кластеру с любым другим узлом.
        ulimits:
            memlock:
                soft: -1
                hard: -1
        tty: true

    whattoread-redis:
        image: redis:6
        restart: always
        volumes:
            - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            TZ: "Europe/Moscow"
