version: "3.7"

services:
  whattoread-nginx:
    container_name: whattoread-nginx
    ports:
        - "8300:80"
    volumes:
      - ./deploy/nginx/prod.conf:/etc/nginx/conf.d/default.conf

  whattoread-php-fpm:
    container_name: whattoread-php-fpm

  whattoread-percona:
    container_name: whattoread-percona
    ports:
      - "3306:3306"
    volumes:
      - whattoread-database-data:/var/lib/mysql
      - ${DB_BACKUPS_PATH}:/home

  whattoread-elasticsearch:
    container_name: whattoread-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m" #Xms обязательно должно быть равно по размеру Xmx. Размер памяти на ноду
    volumes:
      - whattoread-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  whattoread-redis:
    container_name: whattoread-redis
    ports:
      - "6380:6379"
    volumes:
      - whattoread-redis-data:/data

volumes:
  whattoread-database-data: # данные БД
  whattoread-elasticsearch-data: # данные Elasticsearch
  whattoread-redis-data: # данные Redis
