version: "3.7"

services:
    whattoread-nginx:
        ports:
            - "8300:80"
        volumes:
          - ./deploy/nginx/prod.conf:/etc/nginx/conf.d/default.conf
        container_name: whattoread-nginx

    whattoread-php-fpm:
        container_name: whattoread-php-fpm

    whattoread-percona:
      container_name: whattoread-percona
      ports:
        - "3306:3306"
